let wowomensdata = [
    {
        image:
            "https://images.bewakoof.com/t320/killmonger-half-sleeve-t-shirt-509349-1655101044-1.jpg",
        brand: "Bewakoof",
        brand_description: "Men's Black Killmonger Graphic Printed T-shirt",
        price: 240,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Graphic Print",
        fit:"Oversized",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "799",
        member_price: "₹279 for TriBe Members",
    },
    {
        image:
            "https://images.bewakoof.com/t320/killmonger-oversized-fit-t-shirt-509357-1655101091-1.jpg",
        brand: "Bewakoof",
        brand_description:
            "Men's Olive Killmonger Graphic Printed Oversized T-shirt",
        price: 480,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Olive",
        design:"Graphic Print",
        fit:"Oversized",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3",
        sprice: "₹1299",
        member_price: "₹279 for TriBe Members",
    },
    {
        image:
            "https://images.bewakoof.com/t540/men-s-black-kalyug-age-of-machines-graphic-printed-t-shirt-509633-1655211307-1.jpg",
        brand: "Bewakoof",
        brand_description:
            "Men's Black Kalyug Age of Machines Graphic Printed T-shirt",
        price: 240,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Graphic Print",
        fit:"Oversized",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹279 for TriBe Members",
    },
    {
        image:
            "https://images.bewakoof.com/t320/time-flies-oversized-fit-t-shirt-509134-1654873540-1.jpg",
        brand: "Bewakoof",
        brand_description:
            "Men's White Time Flies Graphic Printed Oversized T-shirt",
        price: 500,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "White",
        design:"Graphic Print",
        fit:"Oversized",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1299",
        member_price: "₹469 for TriBe Members",
    },
    {
        image:
            "https://images.bewakoof.com/t320/bugs-bunny-circle-half-sleeve-t-shirt-499256-1652767566-1.jpg",
        brand: "Bewakoof",
        brand_description: "Men's Blue Bugs Bunny Circle Graphic Printed T-shirt",
        price: 390,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Graphic Print",
        fit:"Oversized",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹379 for TriBe Members",
    },
    {
        image:
            "https://images.bewakoof.com/t320/black-full-sleeve-henley-t-shirt-405279-1642406816-1.jpg",
        brand: "Bewakoof",
        brand_description: "Black Full Sleeve Henley T-shirt",
        price: 500,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Plain",
        fit:"Oversized",
        sleeve:"Full Sleeve",
        neck:"Henley",
        ratings:"3.5",
        sprice: "₹949",
        member_price: "₹459 for TriBe Members",
    },
    {
        image:
            "https://images.bewakoof.com/t320/customizable-black-printed-round-neck-t-shirt-443960-1645623796-1.jpg",
        brand: "Bewakoof",
        brand_description: "Customizable Mens Black Round Neck T-shirt",
        price: 500,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Plain",
        fit:"Oversized",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: 840,
        member_price: "₹449 for TriBe Members",
    },
    {
        image:
            "https://images.bewakoof.com/t320/need-space-teddy-half-sleeve-t-shirt-496045-1651841323-1.jpg",
        brand: "Bewakoof",
        brand_description:
            "Men's Black I Need Some Space Teddy Graphic Printed T-shirt",
        price: 700,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Graphic Print",
        fit:"Oversized",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"2.5",
        sprice: 1990,
        member_price: "₹419 for TriBe Members",
    },
    {
        image:
            "https://images.bewakoof.com/t320/the-traveller-full-sleeve-t-shirt-276528-1638212427-1.jpg",
        brand: "Bewakoof",
        brand_description: "The Traveller Full Sleeve T-Shirt",
        price: 200,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "White",
        design:"Print",
        fit:"Oversized",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"3",
        sprice: "₹1299",
        member_price: "₹379 for TriBe Members",
    },
    {
        image:
            "https://images.bewakoof.com/t320/white-half-sleeve-t-shirt-105-1653031889-1.jpg",
        brand: "Bewakoof",
        brand_description: "White Half Sleeve T-Shirt",
        price: 870,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "White",
        design:"Plain",
        fit:"Oversized",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹329 for TriBe Members",
    },
    {
        image:
            "https://images.bewakoof.com/t320/marvel-s-moon-knight-half-sleeve-t-shirt-483814-1648618777-1.jpg",
        brand: "Bewakoof",
        brand_description: "Men's Blue Marvel Moon Knight Graphic Printed T-shirt",
        price: 700,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Graphic Print",
        fit:"Oversized",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹419 for TriBe Members",
    },
    {
        image:
            "https://images.bewakoof.com/t320/men-s-black-the-beatles-graphic-printed-slim-fit-t-shirt-494907-1651066941-1.jpg",
        brand: "Snitch",
        brand_description:
            "Men's Black The Beatles Graphic Printed Slim Fit T-shirt",
        price: 1200,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Graphic Print",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹599",
        member_price: "₹519 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-green-fish-graphic-printed-slim-fit-t-shirt-494927-1651066838-1.jpg",
        brand: "Snitch",
        brand_description: "Men's Green Fish Graphic Printed Slim Fit T-shirt",
        price: 1200,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Green",
        design:"Graphic Print",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3",
        sprice: "₹599",
        member_price: "₹519 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-olive-shuffle-graphic-printed-slim-fit-t-shirt-494923-1651067410-1.jpg",
        brand: "Snitch",
        brand_description: "Men's Olive Shuffle Graphic Printed Slim Fit T-shirt",
        price: 1200,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Olive",
        design:"Graphic Print",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹599",
        member_price: "₹519 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-brown-slim-fit-cotton-t-shirt-494932-1651067132-1.jpg",
        brand: "Snitch",
        brand_description: "Men's Brown Slim Fit Cotton T-shirt",
        price: 1500,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Brown",
        design:"Graphic Print",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹739",
        member_price: "₹739 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-white-slim-fit-shirt-495941-1651673939-1.jpg",
        brand: "Snitch",
        brand_description: "Men's White Slim Fit Shirt",
        price: 1899,
        category: "Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "White",
        design:"Plain",
        fit:"Slim Fit",
        sleeve:"Full Sleeve",
        neck:"Mandarin Collar",
        ratings:"4",
        sprice: 1990,
        member_price: "₹779 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-yellow-space-graphic-printed-slim-fit-t-shirt-494906-1651066922-1.jpg",
        brand: "Snitch",
        brand_description: "Men's Yellow Space Graphic Printed Slim Fit T-shirt",
        price: 1200,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Yellow",
        design:"Graphic Print",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹599",
        member_price: "₹519 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/hangup-kurta-d-greyblacksva-dupion-kurta-kurta-381221-1626783274.jpg",
        brand: "Hangup",
        brand_description: "Kurta",
        price: 777,
        category: "Kurta",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Plain",
        fit:"Relaxed Fit",
        sleeve:"Full Sleeve",
        neck:"Mandarin Collar",
        ratings:"4",
        sprice: "₹3499",
        member_price: "₹659 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/hangup-kurtablack-dupion-shortkurta-kurta-387530-1628520578.jpg",
        brand: "Hangup",
        brand_description: "Kurta",
        price: 1999,
        category: "Kurta",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blace",
        design:"Plain",
        fit:"Relaxed Fit",
        sleeve:"Full Sleeve",
        neck:"Mandarin Collar",
        ratings:"4",
        sprice: "₹2499",
        member_price: "₹629 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/hangup-kurtak76-longkurta-kurta-387523-1628520506.jpg",
        brand: "Hangup",
        brand_description: "Kurta",
        price: 3999,
        category: "Kurta",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Plain",
        fit:"Relaxed Fit",
        sleeve:"Full Sleeve",
        neck:"Mandarin Collar",
        ratings:"4",
        sprice: "₹2999",
        member_price: "₹799 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/hangup-printed-kurta-setsk119kurtaset42-394938-1631598813-1.jpg",
        brand: "Hangup",
        brand_description: "Kurta",
        price: 1990,
        category: "Kurta",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Brown",
        design:"Graphic Print",
        fit:"Relaxed Fit",
        sleeve:"Full Sleeve",
        neck:"Mandarin Collar",
        ratings:"4",
        sprice: "₹3499",
        member_price: "₹949 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/hangup-solid-casual-shirtpurple-hang-up-men-s-shirt-in-pure-cotton-338074-1614335685.jpg",
        brand: "Hangup",
        brand_description: "Solid Casual Shirt",
        price: 2020,
        category: "Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Solid",
        fit:"Regular Fit",
        sleeve:"Full Sleeve",
        neck:"Shirt Collar",
        ratings:"4",
        sprice: 1990,
        member_price: "₹649 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/hangup-kurta-darkbluewhite-linen-kurta-kurta-381231-1626783856.jpg",
        brand: "Hangup",
        brand_description: "Kurta",
        price: 840,
        category: "Kurta",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Solid",
        fit:"Regular Fit",
        sleeve:"Full Sleeve",
        neck:"Mandarin Collar",
        ratings:"4",
        sprice: "₹3999",
        member_price: "₹789 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-grey-striped-cotton-polo-t-shirt-493339-1650913259-1.JPG",
        brand: "Campus Sutra",
        brand_description: "Mens Grey Striped Cotton Polo T-shirt",
        price: 734,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Striped",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Polo",
        ratings:"4",
        sprice: "₹1299",
        member_price: "₹699 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-maroon-blue-color-block-polo-t-shirt-493337-1650913088-1.JPG",
        brand: "Campus Sutra",
        brand_description: "Mens Maroon & Blue Color Block Polo T-shirt",
        price: 589,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Maroon",
        design:"Color Block",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Polo",
        ratings:"4.5",
        sprice: "₹1049",
        member_price: "₹559 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/campus-sutra-men-s-blue-striped-t-shirt73-451561-1637611473-1.jpg",
        brand: "Campus Sutra",
        brand_description: "Mens Blue Striped Regular Fit T-shirt",
        price: 734,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Striped",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: "₹1299",
        member_price: "₹699 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-striped-cotton-shirt-494878-1651067086-1.jpg",
        brand: "Campus Sutra",
        brand_description: "Mens Blue Striped Cotton Shirt",
        price: 1333,
        category: "Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Striped",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Shirt Collar",
        ratings:"3.5",
        sprice: "₹1499",
        member_price: "₹809 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-checked-cotton-shirt-494890-1651067540-1.jpg",
        brand: "Campus Sutra",
        brand_description: "Mens Blue Checked Cotton Shirt",
        price: 1333,
        category: "Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Checked",
        fit:"Regular Fit",
        sleeve:"Full Sleeve",
        neck:"Shirt Collar",
        ratings:"3.5",
        sprice: "₹1499",
        member_price: "₹809 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-yellow-white-striped-cotton-shirt-494856-1651066898-1.jpg",
        brand: "Campus Sutra",
        brand_description: "Mens Yellow & White Striped Cotton Shirt",
        price: 1333,
        category: "Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Yellow",
        design:"Striped",
        fit:"Regular Fit",
        sleeve:"Full Sleeve",
        neck:"Shirt Collar",
        ratings:"4.5",
        sprice: "₹1499",
        member_price: "₹809 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/dillinger-yellow-colourblocked-t-shirt-t-shirt-424934-1640672244.jpg",
        brand: "Dillinger",
        brand_description: "Mens Yellow & White Colourblocked T-shirt",
        price: 500,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Colourblocked",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: "₹1249",
        member_price: "₹469 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/dillinger-green-colourblocked-t-shirt-424875-1633548513-1.jpg",
        brand: "Dillinger",
        brand_description: "Mens Green Colourblocked T-shirt",
        price: 660,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Green",
        design:"Colourblocked",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"2.5",
        sprice: "₹1199",
        member_price: "₹499 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/dillinger-yellow-typography-t-shirt-t-shirt-424517-1634126039.jpg",
        brand: "Dillinger",
        brand_description: "Mens Yellow Typography T-shirt",
        price: 500,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Yellow",
        design:"Typography",
        fit:"Regular Fit",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: "₹1249",
        member_price: "₹479 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/pink-plain-full-sleeves-t-shirt-368604-1638216120-1.jpg",
        brand: "Dillinger",
        brand_description: "Pink Plain Full Sleeves T-shirt",
        price: 550,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Plain",
        fit:"Regular Fit",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: "₹1249",
        member_price: "₹549 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/dillinger-black-striped-t-shirt-424729-1633552176-1.jpg",
        brand: "Dillinger",
        brand_description: "Mens Black & Grey Striped T-shirt",
        price: 498,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Striped",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: "₹899",
        member_price: "₹399 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-purple-graphic-printed-oversized-t-shirt-507597-1654606519-1.jpg",
        brand: "Dillinger",
        brand_description: "Mens Purple Graphic Printed Oversized T-shirt",
        price: 2900,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Purple",
        design:"Graphic Print",
        fit:"Oversized Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: "₹1399",
        member_price: "₹509 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-black-white-color-block-slim-fit-t-shirt-485901-1649068759-1.jpg",
        brand: "Alcis",
        brand_description: "Men's Black & White Color Block Slim Fit T-shirt",
        price: "₹650",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Color Block",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4.5",
        sprice: "₹1199",
        member_price: "₹629 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-grey-printed-slim-fit-t-shirt-485879-1649068364-1.jpg",
        brand: "Alcis",
        brand_description: "Mens Grey Pirnted Slim Fit T-shirt",
        price: "₹500",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Printed",
        fit:"Oversized Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: 1990,
        member_price: "₹479 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-green-be-the-game-typography-slim-fit-t-shirt-485881-1649069025-1.jpg",
        brand: "Alcis",
        brand_description: "Mens Green BE the Game Typography Slim Fit T-shirt",
        price: "₹500",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Green",
        design:"Typography",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: 1990,
        member_price: "₹479 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-grey-think-big-typography-slim-fit-t-shirt-500628-1653036948-1.jpg",
        brand: "Alcis",
        brand_description: "Mens Grey Think Big Typography Slim Fit T-shirt",
        price: "₹899",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Typography",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: "",
        member_price: "₹869 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-pink-warm-up-typography-slim-fit-t-shirt-485592-1649059994-1.jpg",
        brand: "Alcis",
        brand_description: "Men's Pink Warm Up Typography Slim Fit T-shirt",
        price: "₹500",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Pink",
        design:"Typography",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"2.5",
        sprice: 1990,
        member_price: "₹479 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-red-athletics-typography-slim-fit-t-shirt-485882-1649068741-1.jpg",
        brand: "Alcis",
        brand_description: "Men's Red Athletics Typography Slim Fit T-shirt",
        price: "₹600",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Red",
        design:"Typography",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1199",
        member_price: "₹509 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-maroon-all-over-printed-t-shirt-502060-1654867697-1.JPG",
        brand: "Breakbounce",
        brand_description: "Men's Maroon All Over Printed T-shirt",
        price: "₹450",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Maroon",
        design:"All Over Print",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: "₹899",
        member_price: "₹429 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/breakbounce-men-slim-fit-polo-t-shirt-445639-1636453935-1.jpg",
        brand: "Breakbounce",
        brand_description: "Mens Orange Slim Fit Polo T-shirt",
        price: "₹600",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Orange",
        design:"Plain",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Polo",
        ratings:"3.5",
        sprice: "₹1499",
        member_price: "₹569 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/breakbounce-men-round-neck-t-shirt-t-shirt-392550-1641895842.jpg",
        brand: "Breakbounce",
        brand_description: "Mens Pink Graphic Print Round Neck T-shirt",
        price: "₹549",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Pink",
        design:"Graphic Print",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4.5",
        sprice: 1990,
        member_price: "₹509 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/breakbounce-men-regular-fit-printed-t-shirt-445554-1636453632-1.jpg",
        brand: "Breakbounce",
        brand_description: "Mens Grey Regular Fit Printed T-shirt",
        price: "₹450",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Printed",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Regular Fit",
        ratings:"3.5",
        sprice: "₹899",
        member_price: "₹419 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/breakbounce-men-s-coral-red-polo-t-shirt-457795-1639761592-1.jpg",
        brand: "Breakbounce",
        brand_description: "Mens Coral Red Polo T-shirt",
        price: "₹989",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Red",
        design:"Plain",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Polo",
        ratings:"4.5",
        sprice: "₹1799",
        member_price: "₹929 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/breakbounce-men-s-royal-blue-polo-t-shirt-457798-1639762340-1.jpg",
        brand: "Breakbounce",
        brand_description: "Mens Royal Blue Polo T-shirt",
        price: "₹989",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Plain",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Polo",
        ratings:"4.5",
        sprice: "₹1799",
        member_price: "₹929 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/alstyle-printed-men-round-neck-royal-blue-t-shirt-404461-1631707314-1.jpg",
        brand: "Alstyle",
        brand_description: "Printed Men Round Neck Royal Blue T Shirt",
        price: 442,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Printed",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4.5",
        sprice: "₹1099",
        member_price: "₹419 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/alstyle-printed-men-round-neck-navy-t-shirt-404465-1631707134-1.jpg",
        brand: "Alstyle",
        brand_description: "Printed Men Round Neck Navy T Shirt",
        price: 442,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: "₹1099",
        member_price: "₹419 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/alstyle-printed-men-round-neck-maroon-t-shirt-404459-1631707098-1.jpg",
        brand: "Alstyle",
        brand_description: "Printed Men Round Neck Maroon T-Shirt",
        price: 442,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Maroon",
        design:"Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1099",
        member_price: "₹419 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/alstyle-printed-men-round-neck-mustard-t-shirt-404464-1631707063-1.jpg",
        brand: "Alstyle",
        brand_description: "Printed Men Round Neck Mustard T-Shirt",
        price: 442,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Mustard",
        design:"Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"3.5",
        sprice: "₹1099",
        member_price: "₹419 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/alstyle-self-design-men-round-neck-d-grey-t-shirt-393260-1630575775-1.jpg",
        brand: "Alstyle",
        brand_description: "Mens Self Design Round Neck D.Grey T-Shirt",
        price: 200,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹379 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/alstyle-printed-men-round-neck-maroon-t-shirt-411190-1632513929-1.jpg",
        brand: "Alstyle",
        brand_description: "Printed Men Round Neck Maroon T-Shirt",
        price: 442,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Maroon",
        design:"Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"2.5",
        sprice: "₹1099",
        member_price: "₹419 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-black-jeans-497256-1652105273-1.jpg",
        brand: "High Star",
        brand_description: "Mens Black Jeans",
        price: 889,
        category: "Jeans",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"",
        fit:"Regular",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: "₹1699",
        member_price: "₹789 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-slim-fit-jeans-497289-1652104798-1.jpg",
        brand: "High Star",
        brand_description: "Mens Blue SLim Fit Jeans",
        price: 889,
        category: "Jeans",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹2499",
        member_price: "₹929 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-slim-fit-jeans-497296-1652104816-1.jpg",
        brand: "High Star",
        brand_description: "Mens Blue SLim Fit Jeans",
        price: 1135,
        category: "Jeans",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"",
        fit:"Slim Fit",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: "₹2199",
        member_price: "₹1089 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-slim-fit-jeans-497296-1652104816-1.jpg",
        brand: "High Star",
        brand_description: "Mens Blue Slim Fit Jeans",
        price: 1150,
        category: "Jeans",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"",
        fit:"Slim Fit",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: "₹2699",
        member_price: "₹1079 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/high-star-mens-black-washed-slim-fit-mid-rise-jeans-with-belt-loopsmbdrhs1074-jeans-382682-1626875733.jpg",
        brand: "High Star",
        brand_description: "Mens Black Washed Slim Fit Mid Rise Jeans Belt Loopsmbdrhs1074",
        price: "₹828",
        category: "Jeans",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"",
        fit:"Slim Fit",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: "₹2299",
        member_price: "₹789 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/high-star-mens-blue-washed-slim-fit-mid-rise-jeans-with-belt-loopsmbdrhs1035-jeans-382679-1626875681.jpg",
        brand: "High Star",
        brand_description: "Men's Blue Washed Slim Fit Mid Rise Jeans With Belt",
        price: "₹850",
        category: "Jeans",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"",
        fit:"Regular",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: "₹2299",
        member_price: "₹779 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-f-typography-oversized-t-shirt-493400-1650912951-1.jpg",
        brand: "FUGAZEE",
        brand_description: "Mens Blue Typography Oversized T-shirt",
        price: "₹699",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Typography",
        fit:"Oversized",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1199",
        member_price: "₹659 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-all-over-printed-slim-fit-shirt-493418-1650912797-1.jpg",
        brand: "FUGAZEE",
        brand_description: "Mens Blue All Over Printed Slim Fit Shirt",
        price: "₹699",
        category: "Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"All Over Printed",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1599",
        member_price: "₹659 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-red-slim-fit-t-shirt-493424-1650912780-1.jpg",
        brand: "FUGAZEE",
        brand_description: "Mens Red Slim Fit T-Shirt",
        price: "₹599",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Red",
        design:"Plain",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"1.5",
        sprice: "₹1199",
        member_price: "₹569 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-grey-black-all-over-coconut-tree-printed-slim-fit-shirt-493426-1650912909-1.jpg",
        brand: "FUGAZEE",
        brand_description: "Mens Grey & Black All Over Coconut Tree Printed Slim Fit T-Shirt",
        price: "₹699",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"All Over Printed",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1599",
        member_price: "₹659 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-purple-white-see-good-in-all-things-typography-oversized-t-shirt-shorts-set-493434-1650967986-1.jpg",
        brand: "FUGAZEE",
        brand_description: "Men's Purple & White See Good in All Things Typography Oversized T-shirt & Shorts Set",
        price: "₹1399",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Purple",
        design:"Typography",
        fit:"Oversized",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1999",
        member_price: "1339 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-self-design-slim-fit-t-shirt-497661-1652185759-1.jpg",
        brand: "FUGAZEE",
        brand_description: "Mens Blue Self Design Slim Fit T-shirt",
        price: "₹699",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Plain",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1199",
        member_price: "₹699 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-black-95-typography-joggers-462605-1651745461-1.jpg",
        brand: "Blue Tyga",
        brand_description: "Men's Black 95 Typography Joggers",
        price: 500,
        category: "Joggers",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Typography",
        fit:"Regular",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: "₹1499",
        member_price: "₹479 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-95-typography-joggers-462606-1651745607-1.jpg",
        brand: "Blue Tyga",
        brand_description: "Men's Black 95 Typography Joggers",
        price: 500,
        category: "Joggers",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Typography",
        fit:"Regular",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: 500,
        member_price: "₹479 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-grey-slim-fit-trackpant-436183-1652861433-1.jpg",
        brand: "Blue Tyga",
        brand_description: "Men's Grey Slim Fit Trackpant",
        price: "₹549",
        category: "Track Pant",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Typography",
        fit:"Regular",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: "₹1499",
        member_price: "₹509 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-all-over-printed-boxers-pack-of-3-479828-1647254875-1.jpg",
        brand: "Blue Tyga",
        brand_description: "Men's All Over Printed Cotton Boxers (Pack of 3)",
        price: "₹569",
        category: "Boxer",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"All Over Printed",
        fit:"Regular",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: "₹1197",
        member_price: "₹549 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/blue-tyga-men-s-cotton-casual-shorts-with-zipper-pocket-436227-1634566474-1.jpg",
        brand: "Blue Tyga",
        brand_description: "Men's Grey Cotton Casual Short with Zipper Pocket",
        price: 200,
        category: "Shorts",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"",
        fit:"Regular",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: "₹1399",
        member_price: "₹379 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-grey-3-4th-cotton-blend-shorts-462600-1651745552-1.jpg",
        brand: "Blue Tyga",
        brand_description: "Men's Grey 3/4th Cotton Blend Shorts",
        price: "₹419",
        category: "3-4 Th Shorts",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"",
        fit:"Regular",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: "₹1399",
        member_price: "₹399 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/quarantine-brown-solid-t-shirt14-403605-1631622091-1.jpg",
        brand: "Quarantine",
        brand_description: "Brown Solid T-shirt",
        price: "₹378",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Brown",
        design:"Solid",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹899",
        member_price: "₹359 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/quarantine-pink-solid-t-shirt-403579-1631621214-1.jpg",
        brand: "Quarantine",
        brand_description: "Pink Solid T-shirt",
        price: "₹357",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Pink",
        design:"Solid",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹699",
        member_price: "₹339 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/quarantine-red-solid-t-shirt-403571-1631623348-1.jpg",
        brand: "Quarantine",
        brand_description: "Red Solid T-shirt",
        price: "₹249",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Red",
        design:"Solid",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹699",
        member_price: "₹249 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/quarantine-green-solid-t-shirt12-403603-1631621785-1.jpg",
        brand: "Quarantine",
        brand_description: "Green Solid T-shirt",
        price: "₹249",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Green",
        design:"Solid",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹899",
        member_price: "₹299 for TreBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/quarantine-grey-solid-t-shirt19-403610-1631621450-1.jpg",
        brand: "Quarantine",
        brand_description: "Grey Solid T-shirt",
        price: "378",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Solid",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹899",
        member_price: "₹359 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/quarantine-grey-solid-t-shirt-403572-1631623137-1.jpg",
        brand: "Quarantine",
        brand_description: "Grey Solid T-shirt",
        price: "₹357",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Solid",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹699",
        member_price: "₹339 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-black-green-floral-print-cotton-shirt-shorts-set-499079-1652773485-1.jpg",
        brand: "Joven",
        brand_description: "Men's Black & Green Floral Printed Cotton Shirt & Shorts Set",
        price: 1990,
        category: "T-Shirt & Shorts SET",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Floral Print",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹2499",
        member_price: "₹959 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-embroidered-slim-fit-joggers-498814-1652452549-1.jpg",
        brand: "Joven",
        brand_description: "Men's Blue Embroidered Slim Fit Joggers",
        price: "₹649",
        category: "Joggers",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Embroidered",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"",
        ratings:"3.5",
        sprice: "₹1599",
        member_price: "₹619 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-black-grey-checked-cotton-pyjamas-498734-1652452645-1.jpg",
        brand: "Joven",
        brand_description: "Men's Black & Grey Checked Cotton Pyjamas",
        price: "₹649",
        category: "Pyjama",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Checked",
        fit:"Regular",
        sleeve:"",
        neck:"",
        ratings:"3.5",
        sprice: "₹1599",
        member_price: "₹619 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-maroon-embroidered-slim-fit-joggers-498810-1652452450-1.jpg",
        brand: "Joven",
        brand_description: "Mens Maroon Embroidered Slim Fit Joggers",
        price: "₹649",
        category: "Joggers",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Maroon",
        design:"Embroidered",
        fit:"Slim Fit",
        sleeve:"",
        neck:"",
        ratings:"3.5",
        sprice: "₹1599",
        member_price: "₹619 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-black-grey-all-over-printed-cotton-boxers-pack-of-2-496925-1652272819-1.jpg",
        brand: "Joven",
        brand_description: "Menss Black & Grey All Over Printed Cotton Boxers (Pack of 2)",
        price: 500,
        category: "Boxer",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"All Over Printed",
        fit:"Regular",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: "₹1599",
        member_price: "₹479 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-striped-cotton-pyjamas-498740-1652452693-1.jpg",
        brand: "Joven",
        brand_description: "Mens Blue Striped Cotton Pyjamas",
        price: "₹649",
        category: "Pyjama",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Stripe",
        fit:"Regular",
        sleeve:"",
        neck:"",
        ratings:"4",
        sprice: "₹1599",
        member_price: "₹619 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/wtfunk-psy-mandala-backprint-premium-cotton-t-shirt-440291-1639137998-1.jpg",
        brand: "WTFUNK",
        brand_description: "Men's PSY Mandala Backprint Premium Cotton T-shirt",
        price: "₹599",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"All Over Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹99",
        member_price: "₹559 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/wtfunk-workout-doodle-premium-cotton-t-shirt-t-shirt-440259-1640270051.jpg",
        brand: "WTFUNK",
        brand_description: "Men's Workout Doodle Premium Cotton T-shirt",
        price: "₹649",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"All Over Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹619 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/wtfunk-kolkata-travel-doodle-premium-cotton-t-shirt-440247-1639137905-1.jpg",
        brand: "WTFUNK",
        brand_description: "Men's Kolkata Travel Doodle Premium Cotton T-shirt",
        price: "₹649",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"All Over Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹619 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/wtfunk-highway-to-hell-premium-cotton-t-shirt-t-shirt-440270-1640270095.jpg",
        brand: "WTFUNK",
        brand_description: "Men's Highway to Hell Premium Cotton T-shirt",
        price: "₹549",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"All Over Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹519 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/wtfunk-bangalore-travel-doodle-premium-cotton-t-shirt-440254-1639137991-1.jpg",
        brand: "WTFUNK",
        brand_description: "Men's Bangalore Travel Doodle Premium Cotton T-shirt",
        price: "₹649",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "White",
        design:"All Over Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹519 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/wtfunk-pizza-love-premium-cotton-t-shirt-440284-1639137956-1.jpg",
        brand: "WTFUNK",
        brand_description: "Men's Pizza Love Premium Cotton T-shirt",
        price: "₹549",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "White",
        design:"All Over Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹519 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/nammur-men-s-black-stout-beer-print-round-neck-cotton-t-shirt-457591-1639759181-1.jpg",
        brand: "Nammur",
        brand_description: "Men's Black Stout Beer Print Cotton T-shirt",
        price: "₹599",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"All Over Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "",
        member_price: "₹579 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/nammur-men-s-grey-dotted-grey-logo-print-round-neck-cotton-t-shirt-457601-1639759098-1.jpg",
        brand: "Nammur",
        brand_description: "Men's Grey Dotted Grey Typography Cotton T-shirt",
        price: "₹599",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Typograpjy",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "",
        member_price: "₹579 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/nammur-men-s-white-bengaluru-illustration-aw-print-round-neck-cotton-t-shirt-457588-1639758888-1.jpg",
        brand: "Nammur",
        brand_description: "Men's White Bengaluru Illustration AW Print Cotton T-shirt",
        price: "₹699",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "White",
        design:"All Over Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "",
        member_price: "₹679 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/nammur-men-s-blue-bengaluru-illustration-logo-print-round-neck-cotton-t-shirt-457594-1639759322-1.jpg",
        brand: "Nammur",
        brand_description: "Men's Blue Bengaluru Illustration Typography Cotton T-shirt",
        price: "₹549",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Typography",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "",
        member_price: "₹529 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/nammur-men-s-black-bengaluru-illustration-logo-print-round-neck-cotton-t-shirt-457595-1639759284-1.jpg",
        brand: "Nammur",
        brand_description: "Men's Black Bengaluru Illustration Typography Cotton T-shirt",
        price: "₹549",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Typography",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "",
        member_price: "₹529 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/nammur-men-s-black-bengaluru-illustration-aw-print-round-neck-cotton-t-shirt-457593-1639759023-1.jpg",
        brand: "Nammur",
        brand_description: "Men's Black Bengaluru Illustration AW Print Cotton T-shirt",
        price: "₹549",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"All Over Printed",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "",
        member_price: "₹529 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/feel-good-lilac-colorblock-hoodie-t-shirt-453334-1640866574-1.jpg",
        brand: "Bewakoof",
        brand_description: "Hoodie",
        price: 500,
        category: "Hoodie",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "White",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹459 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/biker-bro-454464-1641818672-1.jpg",
        brand: "Bewakoof",
        brand_description: "Hoodie",
        price: "₹379",
        category: "Hoodie",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Red",
        design:"Plain",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1199",
        member_price: "₹359 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/storm-green-half-sleeve-hoodie-t-shirt-436121-1635597459-1.jpg",
        brand: "Bewakoof",
        brand_description: "Hoodie",
        price: 200,
        category: "Hoodie",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Plain",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1149",
        member_price: "₹379 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/blue-qurtz-illuminating-cut-n-sew-hoodie-sweatshirt-392783-1638435450-1.jpg",
        brand: "Bewakoof",
        brand_description: "Hoodie",
        price: 1990,
        category: "Hoodie",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹2349",
        member_price: "₹929 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/toffee-full-sleeve-basic-hoodies-406494-1632980094-1.jpg",
        brand: "Bewakoof",
        brand_description: "Hoodie",
        price: "₹549",
        category: "Hoodie",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Brown",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1499",
        member_price: "₹509 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/bikers-badge-varsity-bomber-jacket-295934-1640064759-1.jpg",
        brand: "Bewakoof",
        brand_description: "Jacket",
        price: "₹739",
        category: "Jacket",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1799",
        member_price: "₹739 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/alcis-men-s-grey-open-front-slim-fit-jacket-459273-1640188317-1.jpg",
        brand: "Alcis",
        brand_description: "Jacket",
        price: "₹1000",
        category: "Jacket",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1999",
        member_price: "₹949 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/orange-plus-size-sleeveless-color-block-puffer-jacket-364918-1642433492-1.jpg",
        brand: "Bewakoof",
        brand_description: "Jacket",
        price: "₹891",
        category: "Jacket",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Plain",
        fit:"Regular",
        sleeve:"Sleeveless",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹3299",
        member_price: "₹839 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/lemon-curry-plus-size-twill-jacket-aw-21-391581-1642489355-1.jpg",
        brand: "Bewakoof",
        brand_description: "Jacket",
        price: "₹1499",
        category: "Jacket",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Yellow",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹3599",
        member_price: "₹1389 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/winter-moss-burnt-orange-plus-size-puffer-jacket-368700-1642433298-1.jpg",
        brand: "Bewakoof",
        brand_description: "Jacket",
        price: "₹1599",
        category: "Jacket",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹4099",
        member_price: "₹1489 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/grey-windcheater-aw-21-364950-1637145757-1.jpg",
        brand: "Bewakoof",
        brand_description: "Jacket",
        price: "₹1149",
        category: "Hoodie",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹2799",
        member_price: "₹1059 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/space-needed-crew-neck-aop-sweatshirt-aw-21-365013-1637924449-1.jpg",
        brand: "Bewakoof",
        brand_description: "Sweatshirt",
        price: "₹749",
        category: "Sweatshirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "White",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1799",
        member_price: "₹699 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/deep-teal-plus-size-crewneck-sweatshirt-aw-21-368671-1637827039-1.jpg",
        brand: "Bewakoof",
        brand_description: "Sweatshirt",
        price: "₹699",
        category: "Sweatshirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "White",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹2049",
        member_price: "₹659 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/be-er-solution-sweatshirt-445274-1640946580-1.jpg",
        brand: "Bewakoof",
        brand_description: "Sweatshirt",
        price: "₹699",
        category: "Sweatshirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Red",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹699",
        member_price: "₹649 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/carmine-crew-neck-cosy-fit-sweatshirt-aw-21-364992-1641471539-1.jpg",
        brand: "Bewakoof",
        brand_description: "Sweatshirt",
        price: 1899,
        category: "Sweatshirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Pink",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1099",
        member_price: "₹739 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/aop-zipper-hoodie-sweatshirt-aw-21-364894-1638534807-1.jpg",
        brand: "Bewakoof",
        brand_description: "Sweatshirt",
        price: "₹1099",
        category: "Sweatshirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Plain",
        fit:"Regular",
        sleeve:"Full Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹2699",
        member_price: "₹1019 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t540/men-s-grey-think-big-typography-slim-fit-t-shirt-500628-1653036948-1.jpg",
        brand: "Alics",
        brand_description: "SweatshirtMen's Grey Think Big Typography Slim Fit T-shirt",
        price: "₹540",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Typography",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹899",
        member_price: "₹519 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-black-color-block-slim-fit-t-shirt-500649-1653036655-1.jpg",
        brand: "Alics",
        brand_description: "Men's Blue & Black Color Block Slim Fit T-shirt",
        price: "₹600",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Grey",
        design:"Color Block",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹579 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-blue-perspective-graphic-printed-slim-fit-t-shirt-500654-1653037476-1.jpg",
        brand: "Alics",
        brand_description: "Men's Blue Perspective Graphic Printed Slim Fit T-shirt",
        price: "₹600",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Graphic Print",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹579 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-black-abstract-printed-slim-fit-t-shirt-500903-1653037035-1.jpg",
        brand: "Alics",
        brand_description: "Men's Black Abstract Printed Slim Fit T-shirt",
        price: "₹780",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Abstract",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1299",
        member_price: "₹759 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-white-color-block-slim-fit-t-shirt-501045-1653059650-1.jpeg",
        brand: "Alics",
        brand_description: "Men's White Color Block Slim Fit T-shirt",
        price: "₹650",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "White",
        design:"Color Block",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1299",
        member_price: "₹629 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t320/men-s-pink-slim-fit-t-shirt-485899-1649068884-1.jpg",
        brand: "Alics",
        brand_description: "Men's Pink Slim Fit T-shirt",
        price: "₹550",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Pink",
        design:"Abstract",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: 1990,
        member_price: "₹529 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t540/campus-sutra-men-s-multicolor-striped-shirt14-451499-1637613437-1.jpg",
        brand: "Campus Sutra",
        brand_description: "Men's Blue & White Striped Regular Fit Shirt",
        price: 1333,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Stripe",
        fit:"Regular Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹1499",
        member_price: "₹809 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t540/men-s-blue-cotton-polo-t-shirt-493355-1650913136-1.JPG",
        brand: "Campus Sutra",
        brand_description: "Men's Blue Cotton Polo T-shirt",
        price: 1333,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Blue",
        design:"Plain",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Polo",
        ratings:"4",
        sprice: "₹1499",
        member_price: "₹809 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t540/campus-sutra-solid-men-polo-neck-green-sports-t-shirtss21-csm-aw-al0689-gre-t-shirt-381116-1626707817.jpg",
        brand: "Campus Sutra",
        brand_description: "Men's Solid Polo Neck Green Sports T-Shirt",
        price: "₹554",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Green",
        design:"Solid",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Polo",
        ratings:"4",
        sprice: 1990,
        member_price: "₹529 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t540/campus-sutra-solid-men-henley-green-t-shirt-t-shirt-366378-1623083365.jpg",
        brand: "Campus Sutra",
        brand_description: "Solid Men's Henley Green T-Shirt",
        price: "₹494",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Green",
        design:"Solid",
        fit:"Regular",
        sleeve:"Half Sleeve",
        neck:"Henley",
        ratings:"4",
        sprice: "₹899",
        member_price: "₹469 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t540/campus-sutra-men-stylish-casual-t-shirt-campus-sutra-men-s-t-shirts-with-mandarin-collar-343514-1616167657.jpg",
        brand: "Campus Sutra",
        brand_description: "Men's Stylish Casual T-Shirt",
        price: "₹494",
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Red",
        design:"Abstract",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Round Neck",
        ratings:"4",
        sprice: "₹899",
        member_price: "₹469 for TriBe Members",
    },
    {
        image: "https://images.bewakoof.com/t540/men-s-pink-cotton-polo-t-shirt-493333-1650913185-1.JPG",
        brand: "Campus Sutra",
        brand_description: "Men's Pink Cotton Polo T-shirt",
        price: 1333,
        category: "T-Shirt",
        sizes: ["X","L","XL","2XL","3XL","28","30","32","34","36","38","40","42","44"],
        color: "Black",
        design:"Abstract",
        fit:"Slim Fit",
        sleeve:"Half Sleeve",
        neck:"Polo",
        ratings:"4",
        sprice: "₹1499",
        member_price: "₹809 for TriBe Members",
    },
    {
      image:
        "https://images.bewakoof.com/t540/one-with-the-universe-boyfriend-t-shirt-483055-1648223195-1.jpg",
      brand_description: "Women's Black One with the Universe Graphic Printed Boyfriend T-shirt",
      price: 599,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/oops-boyfriend-t-shirt-483039-1648528775-1.jpg  ",
      brand_description: "Women's Yellow Oops Graphic Printed Boyfriend T-shirt  ",
      price: 400,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
  
    {
      image:
        " https://images.bewakoof.com/t540/i-decide-my-vibe-boyfriend-t-shirt-479894-1646639984-1.jpg  ",
      brand_description: " Women's Purple I Decide My Vibe Boyfriend Fit T-shirt ",
      price: 300,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/motd-panda-boyfriend-t-shirt-479771-1646211087-1.jpg  ",
      brand_description: " Women's White MOTD Panda T-shirt ",
      price: 500,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/nasa-astronaut-boyfriend-t-shirt-481830-1648011725-1.jpg  ",
      brand_description: " Women's Red NASA Astronaut Boyfriend T-shirt ",
      price: 600,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/music-escape-boyfriend-t-shirt-483052-1648223085-1.jpg  ",
      brand_description: " Women's White Music Escape Printed Boyfriend T-shirt ",
      price: 880,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/nasa-astronaut-boyfriend-t-shirt-481837-1648011703-1.jpg  ",
      brand_description: " Women's Black NASA Astronaut Boyfriend T-shirt ",
      price: 605,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/music-escape-boyfriend-t-shirt-483050-1648223129-1.jpg  ",
      brand_description: "Women's Purple Music Escape Printed Boyfriend T-shirt  ",
      price: 700,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
  
    {
      image:
        " https://images.bewakoof.com/t540/bugs-bunny-boy-friend-fit-tshirt-441317-1644558359-1.jpg   ",
      brand_description: "Women's White Bugs Bunny Oversized T-shirt  ",
      price: 217,
      sprice: "₹899",
      member_price: "₹269 For Tribe Member",
    },
  
    {
      image:
        " https://images.bewakoof.com/t540/jet-black-round-neck-3-4th-sleeve-t-shirt-105769-1637995851-1.jpg  ",
      brand_description: " Women's Black T-shirt ",
      price: 380,
      sprice: 880,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        "https://images.bewakoof.com/t540/jasmin-green-stripe-half-sleeve-t-shirt-473148-1645889994-1.jpg   ",
      brand_description: " Chilled Out Green Stripe T-shirt ",
      price: 100,
      sprice: "₹899",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        "  https://images.bewakoof.com/t540/music-bear-boyfriend-t-shirt-white-329746-1637854875-1.jpg ",
      brand_description: " Women's White Music Bear Boyfriend T-shirt ",
      price: 745,
      sprice: "₹749",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/busy-doin-nothing-boyfriend-t-shirt-dl-pineapple-yellow-277532-1637995596-1.jpg  ",
      brand_description: " Busy Doin Nothing Boyfriend T-Shirt (DL) Pineapple Yellow ",
      price: 555,
      sprice: "₹549",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/jasmin-green-boyfriend-t-shirts-459203-1645889869-1.jpg  ",
      brand_description: " Chilled Out Green Boyfriend T-shirt ",
      price: 520,
      sprice: "₹699",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        "  https://images.bewakoof.com/t540/normal-is-boring-boy-friend-fit-tshirt-441305-1644558127-1.jpg ",
      brand_description: "Women's Black Polka Print Oversized T-shirt  ",
      price: 789,
      sprice: "₹899",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/white-women-s-puff-sleeve-t-shirt-360889-1635869934-1.jpg  ",
      brand_description: " White Women's Puff Sleeve T-Shirt ",
      price: 666,
      sprice: "₹649",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/meteor-grey-boyfriend-t-shirt-211954-1637996010-1.jpg  ",
      brand_description: " Meteor Grey Boyfriend T-Shirt",
      price: 751,
      sprice: 880,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/black-varsity-half-sleeve-round-neck-t-shirt-405982-1637134388-1.jpg  ",
      brand_description: " Women's Black Varsity Half Sleeve Round Neck T-shirt ",
      price: 880,
      sprice: "₹649",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/mickey-colourful-boy-friend-fit-tshirt-441316-1644558389-1.jpg  ",
      brand_description: " Women's White Mickey AOP Oversized T-shirt ",
      price: 980,
      sprice: "₹899",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        "  https://images.bewakoof.com/t540/bold-red-boyfriend-plus-size-boyfriend-t-shirt-326632-1637995844-1.jpg ",
      brand_description: " Bold Red Boyfriend Plus Size Boyfriend T-Shirt ",
      price: 700,
      sprice: "₹749",
      member_price: "₹269 For Tribe Member",
    },
  
    {
      image:
        " https://images.bewakoof.com/t540/bachelor-button-jasmin-green-stripe-short-top-463927-1643558328-1.jpg  ",
      brand_description: " Upbeat Blue Stripe Short Top ",
      price: 840,
      sprice: "₹899",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/climbing-pocket-panda-boyfriend-t-shirt-231686-1640346487-1.jpg  ",
      brand_description: " Climbing Pocket Panda Boyfriend T-Shirt   ",
      price: 880,
      sprice: "₹549",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/magenta-solid-v-neck-top-442909-1645435129-1.JPG  ",
      brand_description: " Magenta Solid V-neck Top   ",
      price: 980,
      sprice: "₹899",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/happy-today-half-sleeve-t-shirts-women-s-half-sleeve-printed-t-shirt-313948-1610098291.jpg  ",
      brand_description: "  Happy Today Half Sleeve T-Shirt  ",
      price: 100,
      sprice: "₹699",
      member_price: "₹269 For Tribe Member",
    },
  
    {
      image:
        " https://images.bewakoof.com/t540/stay-classy-minnie-dl-473316-1645260749-1.jpg  ",
      brand_description: " Women's Yellow Stay Classy Minnie (DL) Slim Fit T-shirt   ",
      price: 751,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
  
    {
      image:
        " https://images.bewakoof.com/t540/pocket-jerry-half-sleeve-t-shirt-tjl-242006-1637843402-1.jpg  ",
      brand_description: "  Women's Red Pocket Jerry Slim Fit T-shirt  ",
      price: 100,
      sprice: "₹549",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/peanuts-yellow-475620-1646117337-1.jpg  ",
      brand_description: "  Women's Blue Typography T-shirt  ",
      price: 751,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/ceylon-yellow-plus-size-pocket-t-shirt-417956-1646129517-1.jpg  ",
      brand_description: " Women's Ceylon Yellow Color Block Relaxed Fit Plus Size T-shirt   ",
      price: 458,
      sprice: "₹1049",
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/enjoy-cola-classic-461287-1645165932-1.jpg  ",
      brand_description: " Enjoy Coca Cola Classic Ringer T-shirt   ",
      price: 980,
      sprice: 1899,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/inner-peace-468836-1645449088-1.jpg  ",
      brand_description: " Inner Peace Women's Varsity Half Sleeve Round Neck T-shirt",
      price: 470,
      sprice: 1899,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        "  https://images.bewakoof.com/t540/misty-pink-round-neck-3-4th-sleeve-t-shirt-206182-1638211396-1.jpg ",
      brand_description: " Misty Pink Round Neck 3/4th Sleeve T-Shirt   ",
      price: 200,
      sprice: 880,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/bachelor-button-side-cut-t-shirt-463560-1643559958-1.jpg  ",
      brand_description: " Upbeat Blue Side Cut T-shirt  ",
      price: 200,
      sprice: "₹899",
      member_price: "₹269 For Tribe Member",
    },
  
    {
      image:
        " https://images.bewakoof.com/t540/bunny-rabbit-pocket-half-sleeve-t-shirt-248178-1638185592-1.jpg  ",
      brand_description: "  Women's Black Bunny Rabbit Pocket Slim Fit T-shirt ",
      price: 200,
      sprice: 980,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/i-ll-be-there-friends-half-sleeve-t-shirt-459797-1644595792-1.jpg  ",
      brand_description: " I'll Be There Friends Half Sleeve T-shirt  ",
      price: 751,
      sprice: 1899,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        "https://images.bewakoof.com/t540/olive-branch-elbow-sleeve-round-neck-t-shirt-422743-1641390443-1.jpg   ",
      brand_description: " Women's Olive Elbow Sleeve Scoop Neck T-shirt  ",
      price: 700,
      sprice: 1899,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/women-s-white-boyfriend-t-shirt-119167-1647430005-1.jpg  ",
      brand_description: " Women's White Boyfriend T-shirt  ",
      price: 751,
      sprice: 880,
      member_price: "₹269 For Tribe Member",
    },
  
    {
      image:
        "https://images.bewakoof.com/t540/scary-list-boyfriend-t-shirt-483035-1648447161-1.jpg",
      brand_description: "Women's Pink Scary List Typography Boyfriend T-shirt",
      price: 200,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        "https://images.bewakoof.com/t540/one-with-the-universe-boyfriend-t-shirt-483055-1648223195-1.jpg",
      brand_description: "Women's Black One with the Universe Graphic Printed Boyfriend T-shirt",
      price: 200,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/oops-boyfriend-t-shirt-483039-1648528775-1.jpg  ",
      brand_description: "Women's Yellow Oops Graphic Printed Boyfriend T-shirt  ",
      price: 200,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
  
    {
      image:
        " https://images.bewakoof.com/t540/i-decide-my-vibe-boyfriend-t-shirt-479894-1646639984-1.jpg  ",
      brand_description: " Women's Purple I Decide My Vibe Boyfriend Fit T-shirt ",
      price: 880,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/motd-panda-boyfriend-t-shirt-479771-1646211087-1.jpg  ",
      brand_description: " Women's White MOTD Panda T-shirt ",
      price: 751,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/nasa-astronaut-boyfriend-t-shirt-481830-1648011725-1.jpg  ",
      brand_description: " Women's Red NASA Astronaut Boyfriend T-shirt ",
      price: 880,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/music-escape-boyfriend-t-shirt-483052-1648223085-1.jpg  ",
      brand_description: " Women's White Music Escape Printed Boyfriend T-shirt ",
      price: 200,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/nasa-astronaut-boyfriend-t-shirt-481837-1648011703-1.jpg  ",
      brand_description: " Women's Black NASA Astronaut Boyfriend T-shirt ",
      price: 880,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
  
    {
      image:
        " https://images.bewakoof.com/t540/i-decide-my-vibe-boyfriend-t-shirt-479894-1646639984-1.jpg  ",
      brand_description: " Women's Purple I Decide My Vibe Boyfriend Fit T-shirt ",
      price: 880,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
    {
      image:
        " https://images.bewakoof.com/t540/motd-panda-boyfriend-t-shirt-479771-1646211087-1.jpg  ",
      brand_description: " Women's White MOTD Panda T-shirt ",
      price: 751,
      sprice: 1990,
      member_price: "₹269 For Tribe Member",
    },
  ];

  let search=document.getElementById("search");
  localStorage.setItem("wp",JSON.stringify(wowomensdata));
  let data=JSON.parse(localStorage.getItem("wp"));
  
  function apnd(data){
      let con=document.querySelector(".products") || document.getElementById("wd");
      con.innerHTML=null;
      con.id="wd";
  
      data.forEach(function(el){
          let box=document.createElement("div");
         box.setAttribute("class","productbox")
          let img=document.createElement('img');
          img.src=el.image;
  
          let brand=document.createElement("p");
          brand.textContent=el.brand_description;
          brand.style.color="grey"
          brand.style.fontWeight="smaller"
  
          let price=document.createElement("h3");
          price.id="pricetext"
          price.textContent=el.price;
  
          let mp=document.createElement("p");
          mp.textContent=el.member_price;
          mp.style.fontWeight="bold";
          mp.style.fontSize="smaller"
          let sprice=document.createElement("p");
          sprice.style.textDecoration="line-througn"
          sprice.textContent=el.sprice
          box.append(img,brand,price,sprice,mp);
          con.append(box);
          
      })
  }

      search.addEventListener("input",function(){
        let fil=wowomensdata.filter(function(el){
            return el.brand_description.toLocaleLowerCase()
            .includes(search.value.toLocaleLowerCase());
        });
        apnd(fil);
      });




  // apnd()
  let myPro=new Promise(function(resolve,reject){
      setTimeout(function(){
          let data=wowomensdata;
          if(data!=null){
              resolve(data);
          }
          else{
              reject("issue from server")
          }
      },6000)
  });
  
  async function main(){
      try{
          let res=await myPro;
          apnd(res);
      }catch(e){
          console.log(e)
      }
  }
  main()
  
  function hl(){
      let data=JSON.parse(localStorage.getItem("wp"));
  
      data=data.sort((a,b)=>b.price-a.price);
      apnd(data);
      console.log(data)
  }
  function lh(){
      let data=JSON.parse(localStorage.getItem("wp"));
      data.sort((a,b)=>a.price-b.price);
      apnd(data)
      console.log(data)
  }